from enum import Enum

class ProposalFileType(Enum):
    EVENT_DESCRIPTION = "EVENT_DESCRIPTION"
    PARTICIPANT_MESSAGE = "PARTICIPANT_MESSAGE"
    TEAM_MESSAGE = "TEAM_MESSAGE"
    DINNER_ROUTE_MESSAGE = "DINNER_ROUTE_MESSAGE"
