version: 2.1

parameters:
  dev-stage-branch:
    type: string
    default: "develop"
  main-stage-branch:
    type: string
    default: "main"

jobs:

  deploy_runningdinner_functions:
    docker:
      - image: cimg/node:current
    environment:
      SERVERLESS_ACCESS_KEY: $PROD_SERVERLESS_ACCESS_KEY
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
            - npm-deps-
      - run:
          name: Install serverless framework and all needed dependencies
          command: |
            yarn install
      - run:
          name: Deploy runningdinner-functions lambda(s)
          command: |
            STAGE="not set"
            if [ $CIRCLE_BRANCH == "<< pipeline.parameters.dev-stage-branch >>" ]; then
              export AWS_ACCESS_KEY_ID=${DEV_AWS_ACCESS_KEY_ID}
              export AWS_SECRET_ACCESS_KEY=${DEV_AWS_SECRET_ACCESS_KEY}
              STAGE="dev"
            else
              export AWS_ACCESS_KEY_ID=${PROD_AWS_ACCESS_KEY_ID}
              export AWS_SECRET_ACCESS_KEY=${PROD_AWS_SECRET_ACCESS_KEY}
              STAGE="prod"
            fi
            # export SERVERLESS_ACCESS_KEY=$PROD_SERVERLESS_ACCESS_KEY
            echo "Starting deploy to $STAGE..."
            npx sls deploy --stage $STAGE --verbose
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: dependencies-{{ checksum "package.json" }}

workflows:
  deploy_functions:
    jobs:
      - confirm-functions-deployment:
          type: approval
          filters:
            branches:
              only:
                - << pipeline.parameters.dev-stage-branch >>
                - << pipeline.parameters.main-stage-branch >>
      - deploy_runningdinner_functions:
          context: workspace
          requires:
            - confirm-functions-deployment
          filters:
            branches:
              only:
                - << pipeline.parameters.dev-stage-branch >>
                - << pipeline.parameters.main-stage-branch >>
